- name: configure all servers 
  hosts: all
  become: true
  tasks:
       - name: "install git, epel release and ntp"
         yum: name= {{ item }} state=present
         with_items:
                   - epel-release
                   - ntp
       - name: start ntpd
         service: name=ntpd state=started
