- name: install node v8
  shell: "curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
"

- name: install node and npm 
  yum: 
     name: "{{ item }}"
     state: installed
  with_items:
            - nodejs
            - git
- name: install forever package
  npm: name=forever state=present global=yes

- name: create nodejs path
  file:
      path: /var/angular/
      state: directory

- name: copy nodejs project
  copy:
      src: goodReads
      dest: /var/angular/good_reads

- name: install required packages
  become_method: sudo 
  become_flags: 'su - root /bin/bash -c'
  command: 'sudo npm install /var/angular/good_reads/goodReads/'
  changed_when: false

- name: install required packages
  command: "cd /var/angular/good_reads/goodReads/ | npm install -g @angular/cli | npm link @angular/cli | npm install"
  changed_when: false

- name: check if angular is running
  command: forever list
  register: forever_list
  changed_when: false

- name: start nodejs app
  command: "forever start /var/angular/good_reads/goodReads/node_modules/@angular/cli/bin/ng serve --host 0.0.0.0"
  when: " forever_list.stdout.find('/var/angulr/good_reads/goodReads') == -1"
